//! C ABI common types for the dynplug plugin interface.

use std::os::raw::c_char;

/// Interface version for host-plugin compatibility.
///
/// Increment when PluginVTable layout changes.
/// This is separate from user-defined plugin versions.
pub const INTERFACE_VERSION: u32 = 1;

/// Default symbol name that plugins export for Layer 2 entry.
///
/// `export_plugin!` macro generates a `#[no_mangle]` function with this name.
/// Custom VTables may use a different symbol name (specified via `vtable()` argument).
pub const PLUGIN_ENTRY_SYMBOL: &str = "plugin_entry";

/// Standard generic VTable for dynplug plugins.
///
/// Auto-generated by `export_plugin!` macro.
/// Users defining custom `#[repr(C)]` VTables (direct Layer 2) need not use this type.
///
/// Field order is frozen for ABI compatibility.
/// New fields must be appended and INTERFACE_VERSION incremented.
#[repr(C)]
pub struct PluginVTable {
    /// dynplug interface version. Must match INTERFACE_VERSION.
    pub interface_version: u32,

    /// Returns the plugin name as a null-terminated UTF-8 string in plugin's static memory.
    /// Host must NOT free the returned pointer.
    pub name: extern "C" fn() -> *const c_char,

    /// Returns the plugin's own version number.
    pub version: extern "C" fn() -> u32,

    /// Generic method invocation.
    ///
    /// # Arguments
    /// - method_ptr, method_len: UTF-8 method name (not null-terminated)
    /// - input_ptr, input_len: Input byte slice. input_ptr may be null if input_len == 0
    /// - out_ptr: On success, plugin writes allocated buffer pointer here
    /// - out_len: On success, plugin writes output buffer length here
    ///
    /// # Return values
    /// -  0: Success. *out_ptr/*out_len contain output. Host must call free_buffer after use.
    ///       If output is empty, *out_ptr = null, *out_len = 0 (no free_buffer needed).
    /// - -1: Application error from plugin. *out_ptr/*out_len contain UTF-8 error message.
    ///       Host must read then call free_buffer.
    /// - -2: Plugin panicked. out_ptr/out_len are undefined. Do NOT call free_buffer.
    pub invoke: extern "C" fn(
        method_ptr: *const u8,
        method_len: usize,
        input_ptr: *const u8,
        input_len: usize,
        out_ptr: *mut *mut u8,
        out_len: *mut usize,
    ) -> i32,

    /// Frees a buffer allocated by invoke.
    ///
    /// Plugin-side allocator owns the memory, so host must NOT dealloc directly.
    /// No-op if ptr is null.
    pub free_buffer: extern "C" fn(ptr: *mut u8, len: usize),

    /// Releases plugin resources.
    ///
    /// Called before Library::close(). Must be idempotent (safe to call multiple times).
    pub destroy: extern "C" fn(),
}

/// Entry point function type.
///
/// Plugins export: `#[no_mangle] pub extern "C" fn plugin_entry() -> *const PluginVTable`
pub type PluginEntryFn = extern "C" fn() -> *const PluginVTable;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_interface_version() {
        assert_eq!(INTERFACE_VERSION, 1);
    }

    #[test]
    fn test_plugin_entry_symbol() {
        assert_eq!(PLUGIN_ENTRY_SYMBOL, "plugin_entry");
    }

    #[test]
    fn test_plugin_vtable_is_repr_c_size() {
        // PluginVTable has 6 fields:
        // u32 (+ padding) + 5 fn pointers
        // On 64-bit: u32(4) + padding(4) + 5*8 = 48 bytes
        let size = std::mem::size_of::<PluginVTable>();
        #[cfg(target_pointer_width = "64")]
        assert_eq!(size, 48, "PluginVTable should be 48 bytes on 64-bit");
        #[cfg(target_pointer_width = "32")]
        assert_eq!(size, 24, "PluginVTable should be 24 bytes on 32-bit");
    }
}
