//! Mel spectrogram accuracy test: compare Rust output against Python WhisperFeatureExtractor.
//!
//! Fixtures generated by Python script using:
//!   WhisperFeatureExtractor(chunk_length=8)
//! Three test signals: silence, 440Hz sine, speech-like (200Hz+400Hz).

use etd::mel::{log_mel_spectrogram, MelConfig};
use std::path::PathBuf;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

/// Load a .npy file containing a 2D f32 array (row-major).
/// Minimal .npy parser: skip header, read remaining bytes as little-endian f32.
fn load_npy_f32(path: &std::path::Path) -> Vec<f32> {
    use std::io::Read;

    let mut file = std::fs::File::open(path)
        .unwrap_or_else(|e| panic!("failed to open {}: {}", path.display(), e));
    let mut buf = Vec::new();
    file.read_to_end(&mut buf).expect("failed to read .npy");

    // .npy format: 6-byte magic + 2-byte version + 2-byte header_len + header + data
    assert_eq!(&buf[..6], b"\x93NUMPY", "not a valid .npy file");
    let header_len = u16::from_le_bytes([buf[8], buf[9]]) as usize;
    let data_start = 10 + header_len;

    let data = &buf[data_start..];
    assert_eq!(
        data.len() % 4,
        0,
        "data length not aligned to f32 (4 bytes)"
    );
    data.chunks_exact(4)
        .map(|chunk| f32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]))
        .collect()
}

/// Load raw f32 PCM samples from a binary file.
fn load_raw_f32(path: &std::path::Path) -> Vec<f32> {
    use std::io::Read;

    let mut file = std::fs::File::open(path)
        .unwrap_or_else(|e| panic!("failed to open {}: {}", path.display(), e));
    let mut buf = Vec::new();
    file.read_to_end(&mut buf).expect("failed to read raw file");

    assert_eq!(buf.len() % 4, 0, "raw file size not aligned to f32");
    buf.chunks_exact(4)
        .map(|chunk| f32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]))
        .collect()
}

/// Compare Rust mel output against Python reference for a single test case.
/// Returns (max_abs_diff, count_exceeding_tolerance).
fn compare_mel(name: &str, audio_file: &str, ref_file: &str, tolerance: f32) -> (f32, usize) {
    let fixtures = fixtures_dir();
    let audio_path = fixtures.join(audio_file);
    let ref_path = fixtures.join(ref_file);

    if !audio_path.exists() || !ref_path.exists() {
        panic!(
            "Fixture files not found for '{}': {} or {}",
            name,
            audio_path.display(),
            ref_path.display()
        );
    }

    let audio = load_raw_f32(&audio_path);
    let config = MelConfig::default();
    let rust_mel = log_mel_spectrogram(&audio, &config);

    let python_mel = load_npy_f32(&ref_path);

    assert_eq!(
        rust_mel.len(),
        python_mel.len(),
        "[{}] mel length mismatch: rust={} vs python={}",
        name,
        rust_mel.len(),
        python_mel.len()
    );

    let mut max_diff: f32 = 0.0;
    let mut diff_count = 0usize;

    for (i, (r, p)) in rust_mel.iter().zip(python_mel.iter()).enumerate() {
        let diff = (r - p).abs();
        if diff > tolerance {
            diff_count += 1;
            if diff_count <= 5 {
                let mel_bin = i / 800;
                let frame = i % 800;
                eprintln!(
                    "[{}] mel[{},{}] (idx={}) rust={:.6} python={:.6} diff={:.6}",
                    name, mel_bin, frame, i, r, p, diff
                );
            }
        }
        max_diff = max_diff.max(diff);
    }

    eprintln!(
        "[{}] max_abs_diff={:.6}  elements_exceeding_tol={}/{}",
        name,
        max_diff,
        diff_count,
        rust_mel.len()
    );

    (max_diff, diff_count)
}

#[test]
fn mel_accuracy_silence() {
    let tolerance = 1e-3;
    let (max_diff, diff_count) = compare_mel("silence", "test_silence.raw", "mel_silence.npy", tolerance);
    assert_eq!(
        diff_count, 0,
        "[silence] {} elements exceed tolerance {}: max_diff={:.6}",
        diff_count, tolerance, max_diff
    );
}

#[test]
fn mel_accuracy_sine440() {
    let tolerance = 1e-3;
    let (max_diff, diff_count) = compare_mel("sine440", "test_sine440.raw", "mel_sine440.npy", tolerance);
    assert_eq!(
        diff_count, 0,
        "[sine440] {} elements exceed tolerance {}: max_diff={:.6}",
        diff_count, tolerance, max_diff
    );
}

#[test]
fn mel_accuracy_speech() {
    let tolerance = 1e-3;
    let (max_diff, diff_count) = compare_mel("speech", "test_speech.raw", "mel_speech.npy", tolerance);
    assert_eq!(
        diff_count, 0,
        "[speech] {} elements exceed tolerance {}: max_diff={:.6}",
        diff_count, tolerance, max_diff
    );
}
